### ISSUE TITLE
ChromeCast API specs

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/chromecast#2]
# ChromeCast Module Specs

Module to communicate with ChromeCasts (CC's)

### Quick example

```javascript
var ChromeCast = require('vigour-chromecast')
var chromecast = new ChromeCast({
  appId: '30C914C1'
})

var castsDetected = chromecast.devices

castsDetected.on('property', function (data) {
  if (data.added) { // new device in the list
    var device = castsDetected[data.added[0]]
    startSession(device) // cast to that device
  }
})

function startSession(device) {
  chromecast.session.val = device
}

function stopSession() {
  chromecast.session.val = false
}

```

### Code Flow

The main file will look at the platform. Three options:

![Code overview](https://www.lucidchart.com/publicSegments/view/da852a12-7cdf-4272-b862-67e67949d6db/image.png)

#### 1 ChromeCast Receiver

If the client is a ChromeCast device, it means the module will become the Receiver API.

The receiver API has the following properties

###### ChromeCast.session

Once a Sender establishes a session with this Receiver, the `session.val` should be set with the `sessionId`.

#### 2 Compatible Sender

If the client is a compatible sender, that means the module will become the Sender API.

##### 2.a Native app (Android / iOS)

The native Senders will use a vigour-wrapper bridge Plugin to enable the Sender API.

The Plugin Object will have the following properties:

###### ChromeCast.appId

When this value is set, the API should initiate.

###### ChromeCast.ready

When the API is ready to be used, this value should be set to true.

###### ChromeCast.devices

This should be a list of available ChromeCast Receiver devices.

###### ChromeCast.devices[*].name

All devices should have `device.name`: Display / Friendly name

###### ChromeCast.devices[*].id

All devices should have `device.id`: Device ID

###### ChromeCast.session

This property can be set with a `device` from `ChromeCast.devices` found at `ChromeCast.devices[*]`.
This will cause a session with that device to be initiated.

`ChromeCast.session.val = false` will stop the session.

###### ChromeCast.session.id

Once a session is established, the sessionId should be set in `ChromeCast.session.id`.

##### 2.b Chrome Browser

In case of the chrome browser, the API will have less features because it will not get a full device list but simply short-cut to the browser plugin to cast to a device. The API will behave the same except for the following properties:

###### ChromeCast.session

The use of `session` is different in Chrome. When it is set to `true`, it should short-cut the user to the Chrome ChromeCast plugin, the user will select a device to cast to from within the plugin.

`ChromeCast.session.val = false` will still stop the session.

`ChromeCast.session.id` will still be set with the `sessionID` once it's established.

###### ChromeCast.devices (removed)

There will be no device list in Chrome.

#### 3 Incompatible

If the client is not a compatible ChromeCast Sender, the API value will be `false`.

**Comment by avdwerff** [comment]
nice

**Comment by marcusbesjes** [comment]
@avdwerff tnx :), @vidbina, @michielibiza 

Could you guys tell me if this makes sense to you? And if does, could you make a time estimate for the work on the native Sender API (iOS / Android)?

I'm going to elaborate more on the vigour-wrapper bridge Plugin remark by documenting a bit more on how the Plugin Observables should work and how they would interact with the bridge.
