### ISSUE TITLE
[Web] Web plugin must detect if already connected

### ISSUE THREAD

**Issue by ninjatux** [vigour-io/chromecast#9]
Currently if we connect to a receiver and we refresh the page we lost the connection. We should be able to get detect if there is a session already active and use that again.

**Comment by renancarvalho** [comment]
So, this is basically handled by chrome cast sender.js when you initialize it.

The second parameter that we need to pass when instantiating the ```new chrome.cast.ApiConfig()``` function, must be a callback(they call it "sessionListener").

This callback will always be called when the ```sender.js api``` detects some content that is already being casted (current alive session).


I just had to change the ```AutoJoinPolicy``` to ```TAB_AND_ORIGIN_SCOPED``` that tells to googlecast, "alright there's something being casted, what should I do ?" in our case, it will automatically join the session.

So whenever a session is alive. if we load the ```sender script``` it will auto join the session.
In our scenario we can get the session Id checking the ```chr.session.chromeSession.sessionId``` property
